name: 'repo-backup-ipfs'
description: 'A GitHub action that backs up your source code to IPFS.'
author: 'Dhaiwat Pandya'
outputs:
  cid:
    description: 'CID of the latest copy of your source code uploaded to IPFS.'
runs:
  using: 'node16'
  main: 'dist/index.js'
